export const MCODE_NOTES: Record<string, string> = {
  'M105': 'Üçüncü şahıslara yapılan brüt yurt içi satışlar. TDHP 600 Yurt İçi Satışlar ana hesabı. TFRS 15 kapsamında hasılat tanıma ilkeleri uygulanır.',
  'M106': 'Bağlı/grup şirketlerine yapılan ihracat satışları. 601 İhracat Satışları',
  'M109': '600+601 hesaplarının toplamı. Yurt içi ve yurt dışı brüt satışlar.',
  'M115': 'Satış hedefi karşılığı müşterilere ödenen ciro primleri. 610 Satıştan İadeler ve İndirimler. Prim faturası KDV Genel Uygulama Tebliği kapsamında düzenlenir.',
  'M116': 'Grup şirketlerine ödenen ciro primleri. Transfer fiyatlandırması belgesi (5 yıl saklama) zorunlu. KVK 13 emsale uygunluk ilkesi.',
  'M120': 'Müşterilerden talep edilen tazminat ve hasar alacakları. Tahsil şüpheli ise 128 + 654 Karşılık Giderleri. Kesinleşmemişse 121 yardımcı hesabında izlenir.',
  'M121': 'Grup/bağlı şirketlerden talep edilen alacaklar. 131 Ortaklardan Alacaklar veya 138 Diğer İlişkili Taraf Alacakları. Transfer fiyatlandırması belgesi zorunlu.',
  'M125': 'Fatura üstü ve sonradan verilen satış iskontoları. 611 Satış İskontoları. Fatura üstü iskonto KDV matrahını düşürür',
  'M126': 'Grup şirketlerine uygulanan ticari iskontolar. 611 altında yardımcı hesap. Emsalsiz iskonto oranları KVK 13 riski doğurur.',
  'M130': 'Müşteriye iade edilen veya üstlenilen nakliye bedeli. 612 Diğer İndirimler. Ayrıca fatura edilmişse 600\'den mahsup yerine 612 kullanımı muhasebe bütünlüğünü korur.',
  'M131': 'Grup şirketlerine iade edilen nakliye bedelleri. Transfer fiyatlandırması belgesi ve emsale uygun fiyat zorunlu.',
  'M139': 'M115+M116+M120+M121+M125+M126+M130+M131 toplamı. 610/611/612 hesap grubunun ana toplamı.',
  'M145': 'Alım-satım faaliyetinden üçüncü şahıslara yapılan ticari mal satışları (brüt). 153 Ticari Mallar stok hesabıyla ilişkili.',
  'M146': 'Grup şirketlerine yapılan ticari mal satışları. Transfer fiyatlandırması kapsamında piyasa fiyatı esas alınır.',
  'M149': 'M145+M146 eksi ilgili iadeler. Ticari mal satışlarının net tutarı',
  'M155': 'Asıl faaliyet dışı hizmet, yan ürün veya atık satışları. 649 Diğer Faaliyetlerden Olağan Gelir ve Karlar altında yardımcı hesap.',
  'M156': 'Grup şirketlerine yapılan diğer satışlar. Transfer fiyatlandırması belgesi zorunlu.',
  'M159': 'M155+M156 toplamı. 649 Diğer Faaliyetlerden Olağan Gelir ve Karlar.',
  'M179': 'M109+M149+M159 eksi M139. Tüm iş kollarından elde edilen net satış gelirlerinin toplamı.',
  'M189': 'Dönem başı ve sonu mamul/yarı mamul stok farkı. 711 Yansıtma hesabı veya 152 Mamuller stok artış/azalışı olarak raporlanır. TMS 2 kapsamı.',
  'M199': 'Net satışlar + stok değişimi. İşletmenin temel faaliyet gelirlerinin tamamı.',
  'M209': 'Ürün sevkiyat, yurt içi/dışı taşıma giderleri. 760 Pazarlama Satış Dağıtım Giderleri altında izlenir. İhracat navlunu için ayrı yardımcı hesap açılabilir.',
  'M215': 'Dış depo kiralama, antrepo ve soğuk hava deposu giderleri. 760 Pazarlama Satış Dağıtım Giderleri. Gümrük antrepo maliyetleri dahil.',
  'M220': 'İthalat/ihracat gümrük vergileri ve harçları. Stok maliyetine eklenmeyip doğrudan gider yazılan kısım 760 altında izlenir.',
  'M225': 'Acentelere, distribütörlere ve satış temsilcilerine ödenen komisyonlar. 760 Pazarlama Satış Dağıtım Giderleri. KDV stopajı değerlendirilmeli.',
  'M226': 'Grup şirketlerine ödenen satış komisyonları. Transfer fiyatlandırması belgesi zorunlu',
  'M230': 'Sevkiyat ve nakliye sürecindeki kargo sigortası giderleri. 760 altında',
  'M235': 'Ambalaj, etiket, sertifika ve diğer satış yan giderleri. 760 Pazarlama Satış Dağıtım Giderleri.',
  'M240': 'Tahsil edilemeyen alacaklar için ayrılan karşılık. 654 Karşılık Giderleri',
  'M245': 'Yukarıdaki satış gider kategorilerine girmeyen çeşitli satış giderleri. 760 Pazarlama Satış Dağıtım Giderleri.',
  'M249': 'M209+M215+M220+M225+M226+M230+M235+M240+M245 toplamı. 760 Pazarlama Satış Dağıtım Giderleri ana hesap grubu.',
  'M299': 'M199 eksi M249. Tüm faaliyet gelirleri eksi satış giderleri. TDHP\'de 60 hesap grubu net satışları ifade eder.',
  'M305': 'Ana üretim hammaddesi ve dışarıdan satın alınan yarı mamul/parça maliyetleri. 710 Direkt İlk Madde ve Malzeme Giderleri (maliyet muhasebesi)',
  'M310': 'Üretimde kullanılan kimyasallar, çözücüler ve katkı maddeleri. 710 altında yardımcı hesapla izlenir. Tehlikeli madde mevzuatı (REACH/RoHS) kapsamında stok takibi önemli.',
  'M315': 'Üretim sırasında tüketilen alet, aparat, tel ve keçe gibi sarf malzemeleri. 710 Direkt veya 730 Genel Üretim Giderleri altında sınıflandırılır.',
  'M320': 'Yağ, ambalaj, temizlik malzemesi gibi dolaylı üretim malzemeleri. 730 Genel Üretim Giderleri altında izlenir.',
  'M325': 'Fason üretim ve dışarıdan sağlanan üretim süreçleri. 730 Genel Üretim Giderleri. Fason faturalarında tevkifat uygulaması (KDV Tebliği) dikkate alınmalı.',
  'M339': 'M305+M310+M315+M320+M325 toplamı. Asıl üretim faaliyetine ait toplam malzeme maliyeti.',
  'M349': 'Ticari mal satışlarının maliyet bedeli. 620 Satılan Ticari Mallar Maliyeti. Dönem sonu stok ile FIFO/ortalama maliyet yöntemi uygulanır (TMS 2).',
  'M359': 'Yukarıdaki kategorilere girmeyen diğer malzeme tüketimleri. 730 Genel Üretim Giderleri altında yardımcı hesap.',
  'M369': 'M339+M349+M359 toplamı. Tüm üretim ve ticaret faaliyetlerine ait malzeme maliyetlerinin genel toplamı.',
  'M399': 'M299 eksi M369. Satış gelirlerinden malzeme maliyetleri düşüldükten sonra kalan brüt katkı payı. Türk tek düzende ayrı hesap yoktur',
  'M405': 'Fabrika ve ofis elektrik tüketim giderleri. Üretimde 730.40, yönetimde 770.40 altında izlenir. Elektrik faturalarında EPDK payı ve enerji fonu ayrıştırılmalı.',
  'M410': 'Doğalgaz, fuel-oil, kömür ve endüstriyel buhar tüketim giderleri. Üretim tesisinde 730.41 altında sınıflandırılır.',
  'M415': 'İşletme su kullanım bedeli. Üretim suyundan ayırt etmek gerekirse 730.42 ile izlenebilir.',
  'M419': 'M405+M410+M415 toplamı. Enerji verimliliği takibi için yardımcı hesap bazında raporlama önerilir.',
  'M450': 'Üretim ve diğer işçilerin brüt maaş/ücret giderleri. Direkt işçilik için 720, endirekt işçilik için 730 veya 770 altında izlenebilir.',
  'M455': 'İşçi ücretleri üzerindeki SGK işveren payı gideri. Borç karşılığı 361 Ödenecek SGK Primleri. 5510 sayılı Kanun kapsamı.',
  'M460': 'İdari ve yönetim personelinin brüt maaş giderleri. 770 Genel Yönetim Giderleri altında izlenir.',
  'M465': 'İdari personel maaşları üzerindeki SGK işveren payı. 361 Ödenecek SGK Primleri karşı hesabı.',
  'M470': 'İş Kanunu 14. madde kapsamında ayrılan kıdem tazminatı karşılığı. 472 Kıdem Tazminatı Karşılığı (pasif)',
  'M475': 'İşveren katkılı BES (Bireysel Emeklilik Sistemi) ve tamamlayıcı emeklilik prim giderleri. Vergi avantajı limitleri (GVK 63/3) dikkate alınmalı.',
  'M480': 'Personele sağlanan sağlık sigortası, eğitim, yemek, servis ve diğer sosyal yardımlar. SGK matrahından istisna limitleri kontrol edilmeli.',
  'M489': 'M450+M455+M460+M465+M470+M475+M480 toplamı. Tüm işçilik maliyetlerinin genel toplamı.',
  'M509': 'Makine, ekipman, bina ve ofis bakım-onarım giderleri. Üretim ekipmanları için 730.20. Aktivasyon sınırını aşan büyük onarımlar duran varlığa eklenir (VUK 272).',
  'M529': 'Çevre izni, atık bertaraf, ÇED ve İş Sağlığı Güvenliği giderleri. 2872 sayılı Çevre Kanunu ve 6331 sayılı İSG Kanunu kapsamı.',
  'M604': 'Fason üretim ve üretim sürecine giren dış personel/hizmetler. 730 Genel Üretim Giderleri. KDV tevkifatı (fason için 7/10) uygulanabilir.',
  'M605': 'İdari süreçlerdeki dışarıdan sağlanan personel/hizmet. 770 Genel Yönetim Giderleri.',
  'M610': 'Ofis, depo, araç kira giderleri. TFRS 16 kapsamında faaliyet/finansal kiralama ayrımı yapılmalı. Finansal kiralamada kullanım hakkı varlığı aktifleştirilir.',
  'M615': 'Yurt içi/dışı iş seyahati, ulaşım, konaklama, harcırah giderleri. GVK harcırah istisna limitleri dikkate alınmalı.',
  'M620': 'Telefon, internet, posta ve kargo giderleri.',
  'M625': 'Avukatlık, YMM/SMMM, iş ve vergi danışmanlığı ücretleri. %20 stopaj uygulaması değerlendirilmeli.',
  'M630': 'Reklam, tanıtım, fuar katılım ve pazarlama giderleri. 760 Pazarlama Satış Dağıtım Giderleri.',
  'M635': 'Yangın, hırsızlık, sorumluluk sigortası giderleri. Peşin ödenen kısım 180 Peşin Ödenmiş Giderler hesabında izlenir.',
  'M640': 'Yazılım lisansı, bulut hizmetleri, IT destek giderleri. Aktivasyon kriterlerini sağlayanlar 260 Haklar altında aktifleştirilir.',
  'M641': 'Grup içi IT fatura paylaşımları. Transfer fiyatlandırması (KVK 13) belgesi zorunlu.',
  'M645': 'Merkezi yönetim ve holding tarafından aktarılan genel gider payları. İlişkili taraf işlemi',
  'M650': 'EFT, havale komisyonu, hesap işletim ücreti. 653 Komisyon Giderleri.',
  'M655': 'Ticari alacak ve borçlardan kaynaklanan kur farkı zararları. 656 Kambiyo Zararları',
  'M660': 'Yukarıdaki kategorilere girmeyen çeşitli genel yönetim giderleri.',
  'M665': 'Damga vergisi, belediye harçları, ÖTV gibi gider yazılabilen vergiler. Kurumlar vergisi bu hesaba alınmaz (691).',
  'M689': 'Olağan dışı nitelikteki çeşitli gider kalemleri. 689 Diğer Olağandışı Gider ve Zararlar.',
  'M705': 'İşletmenin kendi ürettiği veya inşa ettiği duran varlıkların maliyeti aktifleştirilir. 258 Yapılmakta Olan Yatırımlar borçlandırılır',
  'M710': 'Maddi duran varlıkların defter değerinin üzerinde satışından doğan karlar ve yeniden değerleme artışları. 679 Diğer Olağandışı Gelir ve Karlar',
  'M711': 'Grup şirketlerine yapılan duran varlık satışlarından elde edilen karlar. Transfer fiyatlandırması kapsamında emsale uygun fiyat zorunlu.',
  'M715': 'Önceki dönemlerde ayrılan ve ihtiyaç kalmayan karşılıkların iptali. 644 Konusu Kalmayan Karşılıklar hesabı',
  'M720': 'Ticari alacak ve borçlardan kaynaklanan kur farkı karları. 646 Kambiyo Karları',
  'M725': 'Kira geliri, komisyon geliri, hizmet geliri gibi diğer olağan faaliyet gelirleri. 649 Diğer Faaliyetlerden Olağan Gelir ve Karlar.',
  'M726': 'Grup şirketlerinden elde edilen diğer olağan gelirler. Transfer fiyatlandırması belgesi zorunlu.',
  'M739': 'M705+M710+M711+M715+M720+M725+M726 toplamı. 649 hesap grubunun genel toplamı.',
  'M759': 'Finansal kiralama faiz ve giderleri. TFRS 16 kapsamında kullanım hakkı varlığı ve kira yükümlülüğü olarak raporlanır.',
  'M769': 'M799 + M789 (amortisman geri eklenerek hesaplanır). Türk tek düzende ayrı hesap yoktur',
  'M775': 'Bina, makine, demirbaş ve maddi olmayan varlıkların normal amortisman giderleri. 257 Birikmiş Amortismanlar karşı hesap. VUK amortisman oranları veya TMS 16/38 faydalı ömür bazlı.',
  'M780': 'Ticari işletme devrinde oluşan şerefiyenin itfası. TFRS\'de yıllık amortisman yoktur',
  'M785': 'Beklenmedik hasar veya hızlandırılmış amortismanlar. 658 Değer Düşüklüğü Zararları',
  'M787': 'VUK\'ta kabul edilen sınırı aşan amortisman farkları. Vergi matrahına eklenir',
  'M789': 'M775+M780+M785+M787 toplamı. 257 Birikmiş Amortismanlar ve 268 Birikmiş İtfa Payları karşı hesaplar.',
  'M799': 'M769 eksi M789. Finansman giderleri ve vergi öncesi faaliyet karı. Analitik hesaplama ile tespit edilir.',
  'M800': 'İştirak ve bağlı ortaklıklardan alınan kar payları. 640 İştiraklerden Temettü Gelirleri',
  'M801': 'Bağlı ortaklıklardan alınan temettü. 641 hesabı. Yurt içi iştirak temettüsünde KVK 5/1-a istisnası değerlendirilmeli.',
  'M805': 'Hisse senedi, tahvil ve diğer menkul kıymetlerden elde edilen gelirler. 642 Menkul Kıymet Gelirleri.',
  'M806': 'Grup şirketlerinin menkul kıymetlerinden elde edilen gelirler. Transfer fiyatlandırması belgesi zorunlu.',
  'M810': 'Uzun vadeli verilen kredilerden tahakkuk eden faiz gelirleri. 642 altında yardımcı hesap.',
  'M811': 'Grup şirketlerine verilen uzun vadeli kredilerin faiz gelirleri. Örtülü sermaye (KVK 12) ve transfer fiyatlandırması (KVK 13) kuralları değerlendirilmeli.',
  'M815': 'Vadeli mevduat ve diğer banka hesaplarından elde edilen faiz gelirleri. Stopaj kesintisi (GVK geçici 67) dikkate alınmalı.',
  'M816': 'Grup şirketlerine açılan kısa vadeli kredilerin faiz gelirleri. Piyasa faiz oranı esas alınmalı',
  'M820': 'Sınıflandırılamayan diğer finansal gelirler. 649 Diğer Faaliyetlerden Olağan Gelir ve Karlar.',
  'M821': 'Grup şirketlerinden elde edilen diğer finansal gelirler. Transfer fiyatlandırması belgesi zorunlu.',
  'M825': 'Finansal duran varlıklar ve menkul kıymetlerin satışından elde edilen karlar. 645 Menkul Kıymet Satış Karları',
  'M827': 'Finansal borç ve alacaklardan kaynaklanan kur farkı karları. 646 Kambiyo Karları',
  'M829': 'M800 ile M827 arasındaki tüm kalemlerin toplamı. 640-649 finansal gelir hesap grubu.',
  'M835': 'Portföydeki menkul kıymetlerin satışından doğan zararlar. 655 Menkul Kıymet Satış Zararları.',
  'M836': 'Grup şirketlerine ait menkul kıymetlerin satışından doğan zararlar. Transfer fiyatlandırması kapsamında değerlendirilmeli.',
  'M840': 'İştirak, bağlı ortaklık ve menkul kıymetlerde kalıcı değer azalmaları. 657 Değer Düşüklüğü Zararları',
  'M841': 'Grup şirketlerine ait finansal varlıklarda değer azalması. Konsolide finansal tablolarda elimine edilir.',
  'M845': 'Banka kredileri ve kısa vadeli borçlanmaların faiz giderleri. 780 Finansman Giderleri. BSMV (%5) ve KKDF (%0 ihracat, %15 diğer) değerlendirmesi gerekir.',
  'M846': 'Grup şirketlerine ödenen faizler. Örtülü sermaye (KVK 12) ve transfer fiyatlandırması (KVK 13) kuralları kritik',
  'M850': 'Sınıflandırılamayan diğer finansman giderleri. 659 Diğer Finansal Gider ve Zararlar.',
  'M851': 'Grup şirketlerine ödenen diğer finansal giderler. Transfer fiyatlandırması belgesi zorunlu.',
  'M857': 'Finansal borç ve alacaklardan kaynaklanan kur farkı zararları. 656.02 yardımcı hesabı',
  'M859': 'M835+M836+M840+M841+M845+M846+M850+M851+M857 toplamı. 780 Finansman Giderleri + 65 grubu toplamı.',
  'M869': 'M829 eksi M859. Finansal gelirler eksi finansal giderler. Analitik hesaplama ile tespit edilir.',
  'M879': 'M799 + M869. EBIT + Net Finansman Sonucu. 690 hesabına aktarım öncesi ara değer.',
  'M885': 'Beklenmedik, sık olmayan gelirler (kamulaştırma tazminatı, sigorta tazminatı vb.). 679 Diğer Olağandışı Gelir ve Karlar.',
  'M887': 'Beklenmedik, sık olmayan giderler. 689 Diğer Olağandışı Gider ve Zararlar. VUK 197 kapsamında değerlendirme.',
  'M889': 'M885 eksi M887. Türk tek düzende 690 hesabına aktarılır.',
  'M899': 'Tüm gelir ve giderler toplandıktan sonra vergi öncesi kar. 690 Dönem Karı veya Zararı hesabı.',
  'M909': 'Hesaplanan kurumlar vergisi. 691 Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları. 5520 sayılı KVK kapsamı',
  'M910': 'Vergi sonrası dönem net sonucu. 692 Dönem Net Karı veya Zararı hesabı.',
  'M915': 'KKEG kapsamındaki vergi ve kesintiler (trafik cezası, MTV vb.). Vergi matrahına eklenir',
  'M919': 'Dönem sonu kapanış hesabı. 590 Dönem Net Karı veya 591 Dönem Net Zararı. Bilançoda özsermaye altında görünür.',
  'M930': 'Vergi istisnasından yararlanarak ayrılmış fonların kullanımı veya çözümü. 549 Özel Fonlar hesabı.',
  'M935': 'Hisse senedi ihraç primleri veya yeniden değerleme fonlarından yapılan çözümler. 520 Hisse Senedi İhraç Primleri, 521 Hisse Senedi İptal Karları. TTK 462.',
  'M940': 'Yasal yedek veya statü yedeklerinin kullanımı. 540 Yasal Yedekler, 541 Statü Yedekleri. Genel kurul kararı gerekir (TTK 519).',
  'M950': 'Yatırım indirimi veya diğer vergi teşviklerinden yararlanmak amacıyla ayrılan özel fonlar. 549 Özel Fonlar',
  'M955': 'Genel kurul kararıyla ayrılan olağanüstü yedek akçeler. 542 Olağanüstü Yedekler. TTK 519-521 kapsamı',
  'M959': 'M930+M935+M940 eksi M950+M955. Tüm yedek akçe çözüm ve ayrım işlemlerinin net etkisi.',
  'M960': 'Bağlı ortaklıklardaki azınlık hissedarlarına ait kar payı. Konsolide finansal tablolarda 58 Azınlık Payları hesabı',
  'M970': 'Genel kurul kararıyla gerçekleştirilen temettü dağıtımı. 590 Dönem Net Karı borcuna karşı 331 Ortaklara Borçlar veya 500 Sermaye alacaklandırılır. TTK 507-523.',
  'M999': 'Tüm dağıtım ve aktarımlar sonrası nihai kar. 590 Dönem Net Karı hesabında izlenen dağıtılabilir dönem karı.',
};

