export const MCODE_NOTES: Record<string, string> = {
  'M105': 'Üçüncü şahıslara yapılan yurt içi ürün ve hizmet satışları. Türk muhasebesi 600 Yurt İçi Satışlar hesabı.',
  'M106': 'Grup/bağlı şirketlere yapılan yurt dışı satışlar. 601 İhracat Satışları altında izlenir.',
  'M109': '600 ve 601 hesaplarının toplamı. Yurt içi + yurt dışı brüt satış tutarı.',
  'M139': 'Verilen iskontolar, iadeler ve satış indirimleri. 610 Satıştan İadeler, 611 Satış İskontoları.',
  'M149': 'Alım-satım faaliyetinden elde edilen ticari mal satışları (net). 153 Ticari Mallar ile bağlantılı.',
  'M299': 'Brüt satışlardan iade ve indirimler düşüldükten sonra kalan net hasılat. TMS 18 / TFRS 15 kapsamı.',
  'M369': 'Üretimde kullanılan hammadde ve malzeme giderleri. 710 Direkt İlk Madde ve Malzeme Giderleri (maliyet muhasebesi), 150 İlk Madde ve Malzeme (stok).',
  'M399': 'Net gelir eksi değişken maliyetler. Türk tek düzen hesap planında ayrı bir hesap kodu yoktur.',
  'M405': '770 Genel Yönetim Giderleri altında elektrik tüketimi. Üretimde ise 730 Genel Üretim Giderleri altında izlenebilir.',
  'M410': 'Doğalgaz, fuel-oil, kömür ve buhar tüketim giderleri. Üretim tesisinde 730 altında sınıflandırılır.',
  'M415': 'İşletme su kullanım bedeli. Üretim suyundan ayırt etmek gerekirse 730.42 ile izlenebilir.',
  'M419': 'M405+M410+M415 toplamı. Türk muhasebesi için yardımcı hesap kodu ile izlenir.',
  'M489': 'Tüm personelin brüt maaş, ücret, ikramiye giderleri. 720 Direkt İşçilik (üretim) veya 770 Genel Yönetim Giderleri (idari).',
  'M489.01': 'İşverenin karşıladığı sosyal güvenlik prim tutarı. Gider kalemi olarak 770 altında.',
  'M489.02': '4447 sayılı Kanun kapsamında işveren işsizlik sigortası prim gideri (%2). 361 Ödenecek SGK Primleri ile ilişkili.',
  'M489.03': 'Personele sağlanan yemek, yemek kartı ve mutfak giderleri. Kısmen SGK matrahından istisna tutulabilir.',
  'M489.04': 'Personel servis, toplu taşım kartı ve benzeri ulaşım giderleri. SGK matrahından belli limite kadar istisna.',
  'M509': 'Makine, ekipman, bina ve ofis bakım-onarım giderleri. Üretim ekipmanları için 730.20 altında izlenebilir. Büyük onarımlar aktifleştirilebilir.',
  'M529': 'Çevre yönetimi, atık bertaraf, çevre izni ve İş Sağlığı Güvenliği giderleri. Çevre mevzuatı (2872 sayılı Kanun) kapsamı.',
  'M604': 'Fason üretim, kiralık personel ve üretim sürecine giren dış hizmetler. 730 Genel Üretim Giderleri altında izlenir.',
  'M605': 'İdari ve yönetim süreçlerinde kullanılan dışarıdan sağlanan personel/hizmet. 770 Genel Yönetim Giderleri.',
  'M610': 'Ofis, depo, araç kira giderleri. TFRS 16 kapsamında faaliyet kiralaması veya finansal kiralama ayrımı önemlidir.',
  'M615': 'Yurt içi ve yurt dışı iş seyahati, ulaşım, konaklama, harcırah giderleri. Harcırah Kanunu limitleri dikkate alınmalı.',
  'M620': 'Telefon, internet, posta ve kargo giderleri. Fatura bazında 770 altında yardımcı hesapla izlenir.',
  'M625': 'Avukatlık, YMM/SMMM denetim, iş ve vergi danışmanlığı ücretleri. KDV stopajı (%20) uygulanabilir.',
  'M630': 'Reklam, tanıtım, fuar katılım ve pazarlama giderleri. 760 Pazarlama Satış Dağıtım Giderleri ana hesabı altında.',
  'M635': 'Yangın, hırsızlık, sorumluluk sigortası giderleri (nakliye sigortası hariç). Peşin ödenen kısmı 180 Peşin Ödenmiş Giderler.',
  'M640': 'Yazılım lisansı, bulut hizmetleri, IT destek giderleri. Aktivasyon kriterlerini sağlayanlar 260 Haklar altında.',
  'M641': 'Grup içi IT fatura paylaşımları. Transfer fiyatlandırması kurallarına (5520/13) tabi, belgeleme zorunlu.',
  'M645': 'Merkezi yönetim ve holding tarafından aktarılan genel gider payları. İlişkili taraf işlemi.',
  'M650': 'EFT, havale komisyonu, hesap işletim ücreti gibi bankacılık giderleri. 653 Komisyon Giderleri / 659 Diğer Finansal Giderler.',
  'M655': 'Ticari alacak ve borçlardan kaynaklanan kur farkı zararları. 656 Kambiyo Zararları.',
  'M660': 'Yukarıdaki kategorilere girmeyen çeşitli genel yönetim giderleri. Dönem sonunda analiz edilmeli.',
  'M665': 'Damga vergisi, belediye harçları, ÖTV gibi gider yazılabilen vergiler. Kurumlar vergisi bu hesaba alınmaz (691).',
  'M689': 'Olağan dışı nitelikteki çeşitli gider kalemleri. 689 Diğer Olağandışı Gider ve Zararlar hesabı.',
  'M739': 'Asıl faaliyet dışı ancak ticari nitelikteki diğer gelirler (kira geliri, komisyon vb.). 649 Diğer Faaliyetlerden Olağan Gelir ve Karlar.',
  'M759': 'Finansal kiralama (leasing) faiz ve anapara giderleri. TFRS 16 altında kullanım hakkı varlığı ve kira yükümlülüğü ayrımı gerekir.',
  'M769': 'Faiz, Amortisman ve Vergi Öncesi Kar (FAVÖK). Türk tek düzeninde ayrı hesap yoktur.',
  'M775': 'Bina, makine, demirbaş ve maddi olmayan varlıkların normal amortisman giderleri. 257 Birikmiş Amortismanlar karşı hesap.',
  'M780': 'Ticari işletme devrinde oluşan şerefiyenin itfası. TMS 36 altında değer düşüklüğü testi.',
  'M785': 'Beklenmedik değer kayıpları veya hızlandırılmış amortismanlar. 658 Değer Düşüklüğü Zararları.',
  'M787': "VUK'ta kabul edilen sınırı aşan amortisman farkları. Vergi matrahına eklenir.",
  'M789': 'M775+M780+M785+M787 toplamı. 257 Birikmiş Amortismanlar ve 268 Birikmiş İtfa Payları karşı hesaplar.',
  'M799': 'Finansman giderleri ve vergi öncesi faaliyet karı. Türk tek düzeninde analitik hesaplama ile bulunur.',
  'M800': 'İştirak ve bağlı ortaklıklardan alınan kar payları. 640 İştiraklerden Temettü Gelirleri.',
  'M801': 'Bağlı ortaklıklardan alınan temettü. 641 İştiraklerden Temettü Gelirleri (bağlı ortaklık). Vergi istisnası değerlendirmeli.',
  'M805': 'Hisse senedi, tahvil ve diğer menkul kıymetlerden elde edilen gelirler. 642 Menkul Kıymet Gelirleri.',
  'M810': 'Uzun vadeli verilen kredilerden tahakkuk eden faiz gelirleri. 642 altında yardımcı hesapla izlenir.',
  'M815': 'Vadeli mevduat ve diğer banka hesaplarından elde edilen faiz gelirleri. 642.01 yardımcı hesabı veya 643 Faiz Gelirleri.',
  'M820': 'Sınıflandırılamayan diğer finansal gelirler. 649 Diğer Faaliyetlerden Olağan Gelir ve Karlar.',
  'M827': 'Finansal borç ve alacaklardan kaynaklanan kur farkı karları. 646 Kambiyo Karları.',
  'M829': '64 nolu hesap grubunun tamamı. 640-649 arası finansal gelir hesapları.',
  'M835': 'Portföydeki menkul kıymetlerin satışından doğan zararlar. 655 Menkul Kıymet Satış Zararları.',
  'M845': 'Banka kredileri ve kısa vadeli borçlanmaların faiz giderleri. 780 Finansman Giderleri.',
  'M846': 'Grup şirketlerine ödenen faizler. Transfer fiyatlandırması (5520/13) ve örtülü sermaye (5520/12) kurallarına dikkat.',
  'M850': 'Sınıflandırılamayan diğer finansman giderleri. 659 Diğer Finansal Gider ve Zararlar.',
  'M857': 'Finansal borç ve alacaklardan kaynaklanan kur farkı zararları. 656.02 yardımcı hesabı.',
  'M859': '780 Finansman Giderleri + 65 Diğer Faaliyet Giderleri toplamı. TFRS 9 kapsamında sınıflandırma önemli.',
  'M869': 'Finansal gelirler eksi finansal giderler. Türk tek düzeninde analitik hesaplama ile tespit edilir.',
  'M879': 'EBIT + Finansal Sonuç. Türk tek düzeninde 690 hesabına aktarım öncesi ara değer.',
  'M885': 'Beklenmedik, sık olmayan gelirler (kamulaştırma tazminatı, sigorta tazminatı vb.). 679 Diğer Olağandışı Gelir ve Karlar.',
  'M887': 'Beklenmedik, sık olmayan giderler. 689 Diğer Olağandışı Gider ve Zararlar.',
  'M889': '679 - 689 farkı. Türk tek düzende 690 hesabına aktarılır.',
  'M899': 'Tüm gelir ve giderler toplandıktan sonra vergi öncesi kar. 690 Dönem Karı veya Zararı hesabı.',
  'M909': 'Hesaplanan kurumlar vergisi. 691 Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları.',
  'M910': "Vergi sonrası dönem net sonucu. 692 Dönem Net Karı veya Zararı hesabı (590/591'e aktarılmadan önceki değer).",
  'M915': 'KKEG kapsamındaki vergi ve kesintiler (trafik cezası, MTV vb.). Vergi matrahına eklenir.',
  'M919': 'Dönem sonu kapanış hesabı. 590 Dönem Net Karı veya 591 Dönem Net Zararı. Bilançoda özsermaye altında görünür.',
  'M930': 'Vergi istisnasından yararlanarak ayrılmış yedek akçelerin kullanımı. 54 Özel Fonlar ve Yedek Akçeler hesap grubu.',
  'M955': 'Genel kurul kararıyla ayrılan olağanüstü yedek akçeler. 542 Olağanüstü Yedekler.',
  'M999': 'Tüm dağıtım ve aktarımlar sonrası nihai kar. 590 Dönem Net Karı hesabında izlenen dağıtılabilir dönem karı.',
};
